import { Directive, ElementRef, HostListener } from '@angular/core';
import { Router } from '@angular/router';

@Directive({
 selector: '[routerTransformer]'
})
export class RouterTransformerDirective {

  constructor(private elementRef: ElementRef, private router: Router){ }

  //Uses HostListener decorator to capture user clicks getting the events
  @HostListener('document:click', ['$event'])
  //Function that captures the clicks
  public onClick(eve: Event): boolean {
    const element = eve.target as HTMLAnchorElement //const with event of type html anchor
    //Checks if element is a link and if it wasn't generated by Angular
    if (element instanceof HTMLAnchorElement && element.classList.contains('ng-star-inserted') == false) {
      this.router.navigate([element?.getAttribute('href')]); //Navigates to the link in the href attribute
      return false; //returns false so that the browser won't reload
    }
    return true;
  }

}
